/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/model3": {
    get: external["api.model3.get.yaml"]
  };
  "/model1": {
    get: external["api.model1.get.yaml"]
  };
  "/model2": {
    get: external["api.model2.get.yaml"]
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Model3: external["schema.model3.yaml"];
    Model1: external["schema.model1.yaml"];
    Model2: external["schema.model2.yaml"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export interface external {
  "api.model1.get.yaml": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Model1"];
        };
      };
    };
  }
  "api.model2.get.yaml": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Model2"];
        };
      };
    };
  }
  "api.model3.get.yaml": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Model3"];
        };
      };
    };
  }
  "schema.model1.yaml": {
    prop1: string;
  }
  "schema.model2.yaml": {
    prop2: string;
  }
  "schema.model3.yaml": {
    prop3: string;
  }
}

export type operations = Record<string, never>;
